AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for SAM demo application

Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowMethods: "'GET,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Parameters:
  DDBTableName:
    Type: String
    Description: The name of the DynamoDB table

Resources:
  ###################
  ##    Lambdas    ##
  ###################
  # lambda function to load initial data
  LoadDataFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./functions/load_data
      Handler: app.lambda_handler
      Runtime: python3.9 
      FunctionName: LoadDataFunction
      Environment:
        Variables:
          DDBTableName: !Ref DDBTableName
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
              - dynamodb:BatchWriteItem
              Resource: !GetAtt CarTable.Arn
  # lambda function to get car data
  GetCarFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/get_car/
      Handler: app.lambda_handler
      Runtime: python3.9
      FunctionName: GetCarFunction
      Events:
        GetCar:
          Type: Api
          Properties:
            Path: /car
            Method: get
            RequestParameters:
              - method.request.querystring.id
              - method.request.querystring.last_updated
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          DDBTableName: !Ref DDBTableName
      Policies:
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - dynamodb:getItem
            Resource: !GetAtt DocumentTable.Arn

# lambda function to get average data
  GetAvgFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/get_avg/
      Handler: app.lambda_handler
      Runtime: python3.9
      FunctionName: GetAvgFunction
      Events:
        GetAvg:
          Type: Api
          Properties:
            Path: /avg
            Method: get
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          DDBTableName: !Ref DDBTableName
      Policies:
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - dynamodb:getItem
            Resource: !GetAtt DocumentTable.Arn

# API stage
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1

##########################
##    DynamoDB Table    ##
##########################
  # DynamoDB table to store car data
  CarTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: 'id'
          AttributeType: 'N'
        - 
          AttributeName: 'last_updated'
          AttributeType: 'S'
      KeySchema: 
        - 
          AttributeName: 'id'
          KeyType: 'HASH'
        - 
          AttributeName: 'last_updated'
          KeyType: 'RANGE'
      TableName: !Ref DDBTableName
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5